#Assignemnt-05.r
DF <- read.csv("USvideos.csv")
class(DF)
typeof(DF)
View(DF)
library(tidyverse)
vids <- read.csv("USvideos.csv")
DF <- separate(DF,col=publish_time,c("PDate","PTime"),"T",extra="merge")
DF$trending_date <- as.Date(vids$trending_date, "%y.%d.%m")
DF$PDate <- as.Date(DF$PDate, "%Y-%m-%d")
DF$PTime <- as.POSIXct(paste(DF$PDate, DF$PTime), format="%Y-%m-%d %H:%M:%OSZ")
library(stringr)
DF$title <- str_to_title(DF$title)
View(DF)
